version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  mongo-express:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGO_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGO_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGO_SERVER=mongodb
volumes:
  data: {}
networks:
  default:
    name: mongodb-network